version: 2
updates:
  # Frontend Angular
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  # Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions elles-mêmes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
